helm:
  parameters:
  - name: frontend.image
    value: daquan/frontend
    forcestring: true
  - name: frontend.tag
    value: main-d1e5514
    forcestring: true
  - name: backend.image
    value: lyzhang1999/backend
    forcestring: true
  - name: backend.tag
    value: main-2a4bf9a
    forcestring: true
