frontend:
  image: daquan/frontend
  tag: 'cedffd2'
  autoscaling:
    averageUtilization: 90
backend:
  image: daquan/backend
  tag: 'cedffd2'
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
  
